### ISSUE TITLE
build fails..

### ISSUE THREAD

**Issue by burtonator** [jMavarez/Tana#8]
I definitely need something like this too.. I really want the ability to hide the picture when I mouse over.

Anyway.. can't get it to build from HEAD... 

TypeError: Path must be a string. Received undefined
    at assertPath (path.js:28:11)
    at Object.join (path.js:1232:7)
    at directory (webpack:///./src/logger.js?:38:59)
    at eval (webpack:///./src/logger.js?:22:66)
    at Object../src/logger.js (/home/burton/projects/Tana/build/main.js:2072:1)
    at __webpack_require__ (/home/burton/projects/Tana/build/main.js:20:30)
    at eval (webpack:///./src/error.handler.js?:4:65)
    at Object../src/error.handler.js (/home/burton/projects/Tana/build/main.js:2060:1)
    at __webpack_require__ (/home/burton/projects/Tana/build/main.js:20:30)
    at eval (webpack:///./src/app.js?:2:72)
A JavaScript error occurred in the main process
Uncaught Exception:
TypeError: Path must be a string. Received undefined
    at assertPath (path.js:28:11)
    at Object.join (path.js:1232:7)
    at directory (webpack:///./src/logger.js?:38:59)
    at eval (webpack:///./src/logger.js?:22:66)
    at Object../src/logger.js (/home/burton/projects/Tana/build/main.js:2072:1)
    at __webpack_require__ (/home/burton/projects/Tana/build/main.js:20:30)
    at eval (webpack:///./src/error.handler.js?:4:65)
    at Object../src/error.handler.js (/home/burton/projects/Tana/build/main.js:2060:1)
    at __webpack_require__ (/home/burton/projects/Tana/build/main.js:20:30)
    at eval (webpack:///./src/app.js?:2:72)
^C

**Comment by jMavarez** [comment]
Hi Kevin! Would you please tell me which command are you running?

**Comment by kriptontr** [comment]
got same issue with debian stretch  when i run yarn dev or yarn prod

**Comment by jMavarez** [comment]
@burtonator @kriptontr Hope that solves the issue, if anything else comes up let me know!
